apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-events-controller
  namespace: argo-events
  labels:
    app: argo-events-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-events-controller
  template:
    metadata:
      labels:
        app: argo-events-controller
    spec:
      serviceAccountName: argo-events-sa
      containers:
        - name: controller
          image: quay.io/argoproj/argo-events:v1.9.3
          command: ["argo-events-controller"]
          args: []
