apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  nats:
    native:
      replicas: 1
---
# Argo Events installation (controller)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-controller
  namespace: argo-events
  labels:
    app: argo-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-events
  template:
    metadata:
      labels:
        app: argo-events
    spec:
      serviceAccountName: argo-events-sa
      containers:
      - name: controller
        image: quay.io/argoproj/argo-events:v1.9.3
        command: ["argo-events-controller"]
        args: ["eventbus"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events
