apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.37.0
          args:
            - serve
            - /etc/dex/config.yaml
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: config
              mountPath: /etc/dex
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: dex
