wordpressUsername: admin
wordpressPassword: mypassword123
wordpressEmail: admin@miroslavlukac.sk
wordpressBlogName: "Miroslavov blog"

image:
  registry: ghcr.io
  repository: bitnami/wordpress
  tag: 6.4.2

mariadb:
  enabled: true
  image:
    registry: ghcr.io
    repository: bitnami/mariadb
    tag: 11.4.2
  auth:
    rootPassword: rootpass123
    database: wordpress
    username: wpuser
    password: wppass123

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: miroslavlukac.sk
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls: true
  extraHosts:
    - name: www.miroslavlukac.sk
      path: /
  extraTls:
    - hosts:
        - miroslavlukac.sk
        - www.miroslavlukac.sk
      secretName: wordpress-tls

persistence:
  enabled: true
  storageClass: standard
  accessModes:
    - ReadWriteOnce
  size: 5Gi
