apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 19.0.0
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: mypassword123
        wordpressEmail: admin@miroslavlukac.sk
        wordpressBlogName: "Miroslavov blog"

        image:
          registry: docker.io
          repository: bitnamilegacy/wordpress
          tag: 6.0.2-debian-11-r12

        mariadb:
          enabled: true
          image:
            registry: docker.io
            repository: bitnamilegacy/mariadb
            tag: latest
          primary:
            persistence:
              annotations:
                argocd.argoproj.io/sync-options: Prune=false
          auth:
            rootPassword: rootpass123
            database: wordpress
            username: wpuser
            password: wppass123

        service:
          type: ClusterIP

        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: miroslavlukac.sk
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/http01-edit-in-place: "true"
          tls: true
        persistence:
          enabled: true
          storageClass: local-path
          accessModes:
            - ReadWriteOnce
          size: 5Gi
          annotations:
            argocd.argoproj.io/sync-options: Prune=false
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
