apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
  namespace: argo
type: Opaque
stringData:
  client-id: "Ov23liNTqAVq3NCQGwl9"
  client-secret: "b3c3123cdcf0dd1e0572c54fb599e7341e3b8f34"