apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    artifactRepository:
      s3:
        bucket: argo-artifacts
        endpoint: minio.argo.svc.cluster.local:9000
        insecure: true
        accessKeySecret:
          name: minio-credentials
          key: accesskey
        secretKeySecret:
          name: minio-credentials
          key: secretkey
