apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mirec30/gitops-repo
    targetRevision: main
    path: wordpress/helm-values
    chart: wordpress
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      valueFiles:
        - wordpress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
